package com.yaniv.bookshelf.model.enums;

public enum Genre {
    FANTASY, ADVENTURE, ROMANCE, CONTEMPORARY, HORROR, THRILLER, HISTORICAL, SCIENCE,
    MEMOIR, COOKBOOK, ART, SELF_HELP, DEVELOPMENT, MOTIVATIONAL, HEALTH, HISTORY, GUIDE, NONE
}
